# Generated by Django 4.1 on 2022-09-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mydata',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
    ]
